spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: myUser1
    password: password
  liquibase:
    default-schema: public
    change-log: classpath:db.changelog/db.changelog.yaml
    liquibase-schema: public
  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        event:
          listener:
            post-load: ru.clevertec.course.jpa.repository.listener.PostLoadPaymentEventListener





